---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hdfs-aut-tech-v1alpha1-hdfscluster
  failurePolicy: Fail
  name: mhdfscluster.kb.io
  rules:
  - apiGroups:
    - hdfs.aut.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hdfsclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hdfs-aut-tech-v1alpha1-hdfscluster
  failurePolicy: Fail
  name: vhdfscluster.kb.io
  rules:
  - apiGroups:
    - hdfs.aut.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hdfsclusters
  sideEffects: None
