apiVersion: hdfs.aut.tech/v1alpha1
kind: HDFSCluster
metadata:
  name: hdfscluster-single
  namespace: sample
spec:
  nameNode:
    replicas: 1
    resources:
      storage: 5Gi
  dataNode:
    replicas: 3
    resources:
      storage: 10Gi