apiVersion: hdfs.aut.tech/v1alpha1
kind: HDFSCluster
metadata:
  labels:
    app.kubernetes.io/name: hdfscluster
    app.kubernetes.io/instance: hdfscluster-sample
    app.kubernetes.io/part-of: hdfs-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hdfs-operator
  name: hdfscluster-sample
spec:
  # TODO(user): Add fields here
