apiVersion: hdfs.aut.tech/v1alpha1
kind: HDFSCluster
metadata:
  name: hdfscluster-ha
  namespace: sample
spec:
  nameNode:
    replicas: 2
    resources:
      storage: 5Gi
  dataNode:
    replicas: 3
    resources:
      storage: 10Gi
  journalNode:
    replicas: 3
    resources:
      storage: 3Gi
  zookeeper:
    replicas: 3
    resources:
      storage: 3Gi